### ISSUE TITLE
TowerFall Ascension crashing on open

### ISSUE THREAD

**Issue by pVVEN** [cweiske/xposed-ouya-plain-purchases#1]
Per our discussion in the Ouya Saviors Discord server...

When I open TFA, it starts to play the developer credit title video, where "Matt Makes Games" flies onto the screen, but crashes after only a second or two. I went into the Ouya system settings, force-stopped the game and cleared the cache, but it still crashes. I was able to get to the Buy screen before installing the Xposed module.

Let me know if you need any other info and where I might need to find it.

**Comment by cweiske** [comment]
It fetches the undocumented "current_gamer" method:

```
GET /api/v1/developers/a8e5b9f0-1ccd-4cd0-a89e-806170896de8/current_gamer
```

Since the server does not implement that yet it crashes :(

**Comment by cweiske** [comment]
Fixed. I've implemented the current_gamer JSON API endpoint.

**Comment by cweiske** [comment]
http://cweiske.de/ouya-store-api-docs.htm#get-https-devs-ouya-tv-api-v1-developers-xxx-current-gamer
